name: JRPIndicators
version: '${project.version}'
main: jfbdev.jrpindicators.JRPIndicators
api-version: '1.16'
authors: [ jFrostyBoy ]
softdepend: [PlaceholderAPI]
description: RP-индикаторы и уведомления для ролевых серверов

commands:
  rpreload:
    usage: /<command>
    description: Перезагрузка плагина

permissions:
  jrpindicators.admin:
    default: op