name: JRPIndicators
version: '${project.version}'
main: jfbdev.jrpindicators.JRPIndicators
api-version: '1.16'
authors: [ jFrostyBoy ]
softdepend: [PlaceholderAPI]
description: RP-индикаторы и уведомления для ролевых серверов

commands:
  jrpi:
    description: Основная команда плагина
    usage: /jrpi [reload|set <day|month|year> <значение>]
    permission: jrpindicators.admin

permissions:
  jrpindicators.admin:
    description: Доступ к админ-командам
    default: op
